More crossVersion tests

diff --git a/.github/workflows/CrossVersion.yml b/.github/workflows/CrossVersion.yml
--- a/.github/workflows/CrossVersion.yml
+++ b/.github/workflows/CrossVersion.yml
@@ -149,6 +149,7 @@ jobs:
           for folder in osx_v1_0_0 osx_v1_1_3 osx_main linux_main linux_v1_0_0 linux_v1_1_3; do
             for filename in $folder/*; do
               touch $filename.wal && cp $filename.wal a.db.wal 2>/dev/null && cp $filename a.db 2>/dev/null && (./build/release/duckdb a.db -c "ATTACH 'b.db'; COPY FROM DATABASE a TO b;" 2>out || (grep "but it is not a valid DuckDB database file!" out 2>/dev/null || ( echo "--> " $filename && cat out && echo "" && (grep -i "internal error" out && echo "--> " $filename >> report && cat out >> report && echo "" >> report)))) || true
+              ./build/release/duckdb a.db -c "COPY (SELECT any_value(table_name) FROM duckdb_tables()) TO 'table' (HEADER FALSE);" && export TABLE=$(cat table) && echo "COPY (SELECT #1 FROM $TABLE ORDER BY random() LIMIT 1) TO 'value' (HEADER FALSE);" | ./build/release/duckdb a.db && export VALUE=$(cat value) && echo "FROM $TABLE WHERE $VALUE = #1" | ./build/release/duckdb a.db -c || true
               rm -f b.db a.db b.db.wal a.db.wal
             done
           done
@@ -287,7 +288,8 @@ jobs:
           touch report
           for folder in osx_v1_0_0 osx_v1_1_3 osx_main linux_main linux_v1_0_0 linux_v1_1_3; do
             for filename in $folder/*; do
-              touch $filename.wal && cp $filename.wal a.db.wal 2>/dev/null && cp $filename a.db 2>/dev/null && (./build/release/duckdb a.db -c "ATTACH 'b.db'; COPY FROM DATABASE a TO b;" 2>out || (grep "but it is not a valid DuckDB database file!" out 2>/dev/null || ( echo "--> " $filename && cat out && echo "" && (grep -i "internal error" out && echo "--> " $filename >> report && cat out >> report && echo "" >> report)))) || true
+              touch $filename.wal && cp $filename.wal a.db.wal 2>/dev/null && cp $filename a.db 2>/dev/null && (./build/release/duckdb a.db -c "ATTACH 'b.db'; COPY FROM DATABASE a TO b;" 2>out || (grep "but it is not a valid DuckDB database file!" out 2>/dev/null || ( echo "${{ matrix.version }} --> " $filename && cat out && echo "" && (grep -i "internal error" out && echo "--> " $filename >> report && cat out >> report && echo "" >> report)))) || true
+              ./build/release/duckdb a.db -c "COPY (SELECT any_value(table_name) FROM duckdb_tables()) TO 'table' (HEADER FALSE);" && export TABLE=$(cat table) && echo "COPY (SELECT #1 FROM $TABLE ORDER BY random() LIMIT 1) TO 'value' (HEADER FALSE);" | ./build/release/duckdb a.db && export VALUE=$(cat value) && echo "FROM $TABLE WHERE $VALUE = #1" | ./build/release/duckdb a.db -c || true
               rm -f b.db a.db b.db.wal a.db.wal
             done
           done
