Add CrossVersion some

diff --git a/.github/workflows/CrossVersion.yml b/.github/workflows/CrossVersion.yml
--- a/.github/workflows/CrossVersion.yml
+++ b/.github/workflows/CrossVersion.yml
@@ -152,6 +152,85 @@ jobs:
               rm -f b.db a.db b.db.wal a.db.wal
             done
           done
+  osx-step-3:
+    # Builds binaries for linux
+    name: OSX Release test
+    runs-on: macos-14
+    needs:
+      - osx-step-1
+      - linux-step-1
+    strategy:
+      matrix:
+        version: [ 'v1.1.3', 'main' ]
+    env:
+      EXTENSION_CONFIGS: '${GITHUB_WORKSPACE}/.github/config/bundled_extensions.cmake'
+      CORE_EXTENSIONS: 'sqlsmith'
+      ENABLE_EXTENSION_AUTOLOADING: 1
+      ENABLE_EXTENSION_AUTOINSTALL: 1
+      GEN: ninja
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ matrix.version }}
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+
+      - name: Install Ninja
+        run: brew install ninja
+
+      - name: Setup Ccache
+        uses: hendrikmuhs/ccache-action@main
+        with:
+          key: ${{ github.job }}
+          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}
+
+      - name: Build
+        shell: bash
+        run: make
+
+      - name: Print platform
+        shell: bash
+        run: ./build/release/duckdb -c "PRAGMA platform;"
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: files-osx-v1.0.0
+          path: osx_v1_0_0
+      - uses: actions/download-artifact@v4
+        with:
+          name: files-osx-v1.1.3
+          path: osx_v1_1_3
+      - uses: actions/download-artifact@v4
+        with:
+          name: files-osx-main
+          path: osx_main
+      - uses: actions/download-artifact@v4
+        with:
+          name: files-linux-v1.0.0
+          path: linux_v1_0_0
+      - uses: actions/download-artifact@v4
+        with:
+          name: files-linux-v1.1.3
+          path: linux_v1_1_3
+      - uses: actions/download-artifact@v4
+        with:
+          name: files-linux-main
+          path: linux_main
+
+      - name: Cross test
+        shell: bash
+        run: |
+          touch report
+          for folder in osx_v1_0_0 osx_v1_1_3 osx_main linux_main linux_v1_0_0 linux_v1_1_3; do
+            for filename in $folder/*; do
+              touch $filename.wal && cp $filename.wal a.db.wal 2>/dev/null && cp $filename a.db 2>/dev/null && (./build/release/duckdb a.db -c "FROM sqlsmith(max_queries=100, verbose_output=1); FROM fuzzyduck(max_queries=20, verbose_output=1);" 2>out || (grep "but it is not a valid DuckDB database file!" out 2>/dev/null || ( echo "--> " $filename && cat out && echo "" && (grep -i "internal error" out && echo "--> " $filename >> report && cat out >> report && echo "" >> report)))) || true
+              rm -f b.db a.db b.db.wal a.db.wal
+            done
+          done
 
       - name: Internal error report
         shell: bash
